package dicoding.rizkynugrahaherliyanto.com.heromobilelegendspedia;

import java.util.ArrayList;

public class ArrayDataHero {
    public static String[][] data = new String[][]{
            {"Vexana", "Mage", "https://vignette.wikia.nocookie.net/mobile-legends/images/0/0a/Vexana.png","poke/crowd control","32000","599","Necromancy Spell - Passive", "Charmed Specter", "Nether Snare", "Cursed Oath", "https://vignette.wikia.nocookie.net/mobile-legends/images/7/72/Necromancy_Spell.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/7/79/Charmed_Specter.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/54/Nether_Snare.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/59/Cursed_Oath.png", "Summoner yang bengkok menambah mantra okult pada target yang menerima damage dari Necromancer, yang berlangsung selama 5 detik. Ketika mantera berlangsung, target akan meledak pada saat kematian, menghasilkan 32 = ~ 600 (Total Magic Power 50%) poin Magic Damage ke unit sekitarnya (kerusakan basis meningkat dengan level).", "Vexana melepaskan kekuatan hantu ke depan, memberikan 280 (+ 60% Total Magic Power) poin Magic Damage. Hit heroes akan kehilangan kontrol dan berputar di suatu tempat selama 1 detik.",
                    "\nMemanggil kekuatan dunia lain untuk menangani 500 (+ 200% Total Kekuatan Sihir) poin Kerusakan Sihir ke lokasi tertentu.",
                    "\nVexana mengutuk pahlawan musuh yang bertahan 8 detik (tidak dapat dihilangkan secara aktif), dan memberikan 250 (+ 80% Total Kekuatan Sihir) poin Magic Damage, ditambah poin 75 (+ 20% Total Magic Power) tambahan dari Magic Kerusakan per detik."},

            {"Claude", "Marksman", "https://vignette.wikia.nocookie.net/mobile-legends/images/0/0b/Claude.png","reap/burst","32000","599","Battle Side-By-Side - Passive", "Art of Thievery",
                    "Battle Mirror Image", "Blazing Duet", "https://vignette.wikia.nocookie.net/mobile-legends/images/9/91/Battle_Side-By-Side.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/8/8f/Art_of_Thievery.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/51/Battle_Mirror_Image.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/0/0c/Blazing_Duet.png", "Dexter meluncurkan serangan untuk membantu Claude. Penawaran 35% dari kerusakan Claude dalam kerusakan bonus untuk unit musuh yang rusak oleh serangan dasar Claude. (Dexter juga menikmati bonus serangan dasar)\n" +
                    "\n.", "Claude menyerang musuh dalam area berbentuk kipas, memberikan 160 (+ 40% Total Serangan Fisik) poin dari Kerusakan Fisik dan mengurangi Kecepatan Gerakan mereka sebesar 20% dan Kecepatan Serangan sebesar 10%..",
                    "Claude menggunakan perangkat Dr. Rooney untuk meninggalkan gambar cermin Dexter di lokasi yang ditentukan. Gambar cermin Dexter secara otomatis menyerang unit musuh.",
                    "Claude dan Dexter melepaskan serangan rentetan, memberikan kerusakan terus menerus pada musuh di dalam area sekitar duo. Berlangsung selama 3 detik. Setiap serangan memberikan 80 (+ 10% Total Serangan Fisik) poin Kerusakan Fisik ke unit musuh."},

            {"Grock", "Tank", "https://vignette.wikia.nocookie.net/mobile-legends/images/2/2b/Grock.png","initiator/crowd control","32000","599","Ancestral Gift - Passive", "Power of Nature", "Guardian's Barrier", "Wild Charge", "https://vignette.wikia.nocookie.net/mobile-legends/images/3/3b/Ancestral_Gift.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/4/4a/Power_of_Nature.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/1/12/Guardian%27s_Barrier.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/5b/Wild_Charge.png", "Meningkatkan kecepatan gerakannya sebesar 10%, dan 26-180 pertahanan fisik dan magis (meningkat seiring level) ketika Grock berada di dekat dinding atau menara..", "Mengangkat senjata untuk menyapu musuh di dekatnya, memberikan 300/360/420/480/540/600 kerusakan fisik dan memperlambat kecepatan gerakan mereka selama 2 detik. Semakin lama dia mengisi, semakin tinggi kerusakannya.",
                    "\nMenyalakan gelombang kejut ke lokasi target, memberikan 300/330/360/390/420/450 kerusakan fisik. Kemudian gelombang kejut menjadi dinding batu yang menghalangi musuh selama 5 detik.",
                    "\nCharges forward, dealing 300/400/500 physical damagee to enemies on the path. Hitting a wall or a turret allows him to deal 900/1200/1500 physical damage to the nearby enemies and reduce cooldown of this skill by 30%."},

            {"Gusion", "Assassin/Mage", "https://vignette.wikia.nocookie.net/mobile-legends/images/b/b2/Gusion.png","charge/burst","32000","599","Dagger Specialist - Passive", "Sword Spike", "Shadowblade Slaughter", "Incandescence", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/56/Dagger_Specialist.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/1/1c/Sword_Spike.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/c/c8/Shadowblade_Slaughter.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/52/Incandescence.png", "Setiap spellcast menambahkan tanda pada belati Gusion. Setelah menumpuk 3 rune, serangan dasar berikutnya akan memberikan kerusakan tambahan sama dengan 15% dari HP yang hilang target, dan mengembalikan HP sama dengan 85% dari kesepakatan kerusakan.", "Melempar belati ke arah yang ditentukan, memberikan 200 (+ 80% Total Magic Power) Magic Damage ke target target pertama. Gunakan skill ini lagi untuk muncul di belakang target dan serang mereka untuk 200 (+ 150% Kekuatan Sihir Total) Kerusakan Sihir.",
                    "\nMelempar belati ke depan, masing-masing menangani 130 (+ 60% Total Kekuatan Sihir) Kerusakan Ajaib untuk target mengenai dan memperlambat mereka selama 2 detik.",
                    "\nBerlari ke lokasi yang ditentukan, segeralah menyegarkan Sword Spike dan cooldown Shadowblade Slaughter. Keterampilan ini dapat digunakan lagi setelah jeda singkat untuk berlari jarak pendek ke arah yang ditentukan."},

            {"Alpha", "Fighter", "https://vignette.wikia.nocookie.net/mobile-legends/images/a/a8/Alpha.png","charge/damage","32000","599","Beta, Advance! - Passive", "Rotary Impact", "Force Swing", "Spear of Alpha", "https://vignette.wikia.nocookie.net/mobile-legends/images/1/15/Beta%2C_Advance%21.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/b/ba/Rotary_Impact.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/8/89/Force_Swing.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/5e/Spear_of_Alpha.png", "Menggunakan skill akan memanggil Beta untuk menyerang dan menandai target. Beta akan menyerang target secara terus-menerus setelah 2 mark, memberikan total 150 poin dari damage sebenarnya.", "Meluncurkan garis miring ke depan, memberikan 210/230/250/270/290/310 poin kerusakan fisik kepada musuh di sepanjang jalan dan menurunkan kecepatan gerakan mereka 70%, tahan 2 detik.",
                    "\nSetelah menyalakan untuk sementara waktu, pahlawan akan menyerang ke depan di daerah berbentuk kerucut dan memberikan 160/220/280/340/400/460 poin kerusakan fisik pada musuh dan memperlambatnya.",
                    "\nPegang tombak cahaya dengan kuat, memukau target saat hits. Pahlawan akan ditarik ke musuh yang terkena, menangani 245/305/365 poin kerusakan fisik kepada musuh di sepanjang jalan."},

            {"Kimmy", "Marksman/Mage", "https://vignette.wikia.nocookie.net/mobile-legends/images/6/65/Kimmy.png","damage/poke","32000","599","Chemist's Instinct - Passive", "Energy Transformation", "Chemical Refinement", "Maximum Charge", "https://vignette.wikia.nocookie.net/mobile-legends/images/1/1e/Chemist%27s_Instinct.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/0/0c/Energy_Transformation.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/8/82/Chemical_Refinement.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/5/5c/Maximum_Charge.png", "Kimmy terobsesi dengan kreasi kimianya. Akibatnya, dia bisa bergerak dan membidik ke arah lain ketika menggunakan pistol semprot tetapi seringkali kurang akurat. Semua bonus Kecepatan Serangannya akan dikonversi menjadi bonus Kecepatan Gerakan.",
                    "\nKimmy mencampur zat-zat dalam Coalescer-nya dan menembakkan bola-bola kimia yang menghasilkan 25/28/31/34/47/40 (+ 40% Total Serangan Fisik) (+ 45% Total Kekuatan Sihir) poin Magic Damage.",
                    "\nKimmy menciptakan jenis campuran kimia baru. Dia kemudian menembakkan semprotan kimia sementara recoil mendorongnya ke belakang.","Kimmy menyalurkan sihir api yang kuat ke senapannya untuk memaksimalkan tekanan outputnya, menciptakan serangan kimia bercahaya."},

            {"Angela", "Support/Mage", "https://vignette.wikia.nocookie.net/mobile-legends/images/f/fd/Angela.png","regen/poke","24000","499","Smart Heart - Passive", "Love Waves", "Puppet-on-a-String", "Heartguard", "https://vignette.wikia.nocookie.net/mobile-legends/images/7/7b/Smart_Heart.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/8/88/Love_Waves.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/a/a6/Puppet-on-a-String.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/a/a0/Heartguard.png", "Setiap kali Angela menggunakan skill, kecepatan gerakannya meningkat 10% untuk 4s, hingga 30%. Efek percepatan ini juga akan diterapkan pada sekutunya yang terlampir.", "Meluncurkan energi cinta ke arah yang ditentukan, memberikan 200 (+3) kerusakan sihir dan menambahkan Lover's Mark. Setiap tumpukan Lover's Mark meningkatkan damage yang diambil sebesar 10% dan mengurangi kecepatan gerakan hingga 15%.",
                    "\nMeluncurkan string boneka pada target yang ditentukan, menangani 300 (+11) kerusakan sihir. Jika target masih terhubung ke string setelah 3s, mereka akan diimobilisasi selama 2s dan mengambil 450 (+17) damage magic.",
                    "\nAngela mengumpulkan energi untuk menghasilkan perisai untuk target ramah, menyerap 1.200 (+78) kerusakan untuk 3 detik. Setelah periode waktu tertentu, ia menjadi terikat dengan target ramah untuk 12-an."},

            {"Lancelot", "Assassins", "https://vignette.wikia.nocookie.net/mobile-legends/images/c/cd/Lancelot.png","charge/burst","32000","599","Soul Cutter - Passive", "Puncture", "Thorned Rose", "Phantom Execution", "https://vignette.wikia.nocookie.net/mobile-legends/images/4/42/Soul_Cutter.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/3/35/Puncture.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/3/32/Thorned_Rose.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/9/9d/Phantom_Execution.png", "Untuk setiap 10-an, Lancelot akan menyelesaikan 'janji bedah' pagar anggar, serangan dasar berikutnya akan membuat target tidak berdaya, Lancelot akan memberikan kerusakan tambahan 20% untuk musuh yang tidak berdaya.", "Tuduhan menuju arah yang ditargetkan menangani 100/130/160/190/220/250 poin kerusakan fisik, target akan terukir dengan tanda pedang.",
                    "\nMelakukan teknik pedang yang luar biasa dalam area yang dapat menyerang musuh hingga 3 kali, memberikan 250/290/330/370/410/450 kerusakan fisik dan memperlambat musuh sebesar 3% untuk 1s pada setiap pukulan.",
                    "\nSetelah periode pengisian yang singkat, Lancelot melakukan serangan algojo ke arah depan, ia tidak terkalahkan di seluruh proses, memberikan 400/600/800 poin kerusakan fisik kepada musuh-musuhnya."},

            {"Lolita", "Tank", "https://vignette.wikia.nocookie.net/mobile-legends/images/2/22/Lolita.png","crowd control/push","32000","599","Noumenon Energy Core - Passive", "Charge!", "Guardian's Bulwark", "Noumenon Blast", "https://vignette.wikia.nocookie.net/mobile-legends/images/7/7b/Noumenon_Energy_Core.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/1/17/Charge%21.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/6/62/Guardian%27s_Bulwark.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/6/6a/Noumenon_Blast.png", "Setiap kali Lolita tidak mengalami kerusakan selama 5 detik berturut-turut, Noumenon Energy Core akan mengisi ulang secara perlahan, untuk sementara memberi Lolita dan sekutu terdekatnya perisai ketika dengan biaya maksimum.",
                    "\nLolita mengangkat perisainya untuk mengunci semua serangan dasar dan proyektil masuk yang masuk. Setelah shieLd jatuh, ketuk skill lagi untuk meluncurkan Energy Blast deal 400 (+ 50% Serangan Fisik).","Biaya menuju arah target, meningkatkan serangan kerusakan dasar dan jangkauan dalam 5 detik berikutnya dan mengurangi kecepatan gerakan target sebesar 20% saat dipukul. Mengisi musuh. menangani 350 + 2,5% dari kesehatan maksimum target sebagai Kerusakan Fisik sementara juga mempesona mereka selama 0,8 detik.",
                    "\nLolita mendapatkan efek perisai pasif, lalu setelah mengisi daya selama 2 detik. memberikan 350 (+ 100% Total Serangan Fisik) - 700 (+ 200% Total Serangan Fisik) di sebuah kerucut di depannya. Saat melakukan casting dengan biaya maksimal."},

            {"Guinevere", "Fighter/Mage", "https://vignette.wikia.nocookie.net/mobile-legends/images/8/89/Guinevere.png","charge/burst","32000","599","Super Magic - Passive", "Enery Wave", "Magic Thump", "Violet Requiem", "https://vignette.wikia.nocookie.net/mobile-legends/images/2/21/Super_Magic.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/8/89/Energy_Wave.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/f/fe/Magic_Thump.png", "https://vignette.wikia.nocookie.net/mobile-legends/images/0/04/Violet_Requiem.png", "Ketika Guinevere memberikan 25% damage ekstra untuk menghajar musuh. Musuh yang merusak menagih Super Magic-nya, ketika sudah penuh serangan dasar berikutnya akan ditingkatkan.", "Guinevere mengirimkan bola energi ke arah yang ditentukan, memberikan 300/345/390/435/480/525 (+ 130% Total Kekuatan Sihir) poin Magic Damage ke musuh pertama yang memukul dan memperlambatnya hingga 70%.",
                    "\nGuinevere melompat ke tempat yang ditentukan. Jika dia mengenai musuh, dia akan menjatuhkan mereka selama 1 detik dan memberikan 250 (+ 80% Total Kekuatan Sihir) poin Kerusakan Sihir kepada mereka. Tidak lama setelah menggunakan skill ini, ia mendapatkan skill baru Migrasi Spasial.",
                    "\nGuinevere melepaskan sihir supernya, memberikan 500/700/900 (+ Total Kekuatan Sihir 500%) poin Kerusakan Sihir kepada musuh terdekat dalam waktu 2 detik. Jika musuh dihancurkan ketika Guinevere melemparkan skill ini, mereka akan dihajar 6 kali lagi."},
    };
    public static ArrayList<Heroes> getListData(){
        ArrayList<Heroes> list = new ArrayList<>();
        for (String[] aData : data) {
            Heroes hero = new Heroes();
            hero.setNama(aData[0]);
            hero.setRole(aData[1]);
            hero.setPhoto(aData[2]);
            hero.setSpecial(aData[3]);
            hero.setGold(aData[4]);
            hero.setDiamond(aData[5]);
            hero.setNmskill1(aData[6]);
            hero.setNmskill2(aData[7]);
            hero.setNmskill3(aData[8]);
            hero.setNmskill4(aData[9]);
            hero.setImgskill1(aData[10]);
            hero.setImgskill2(aData[11]);
            hero.setImgskill3(aData[12]);
            hero.setImgskill4(aData[13]);
            hero.setDecskill1(aData[14]);
            hero.setDecskill2(aData[15]);
            hero.setDecskill3(aData[16]);
            hero.setDecskill4(aData[17]);

            list.add(hero);
        }
        return list;
    }

}

